<a href="https://colab.research.google.com/github/SriSharanya-617/attentionmechanism/blob/main/Attentionmechanism_encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Attention Mechanism

In [ ]:
import numpy as np
from tensorflow.keras.models import Model

from tensorflow.keras.layers import(
Input,
LSTM,
Embedding,
Dense,
Attention,
Concatenate

)


from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
english_sentences = [
    "hi",
    "how are you",
    "i am good",
    "good morning",
    "good evening",
    "good night",
    "i love deep learning",
    "i love ai",
    "what is your name",
    "my name is google assistant",
    "i like to learn",
    "tell me about yourself",
    "where are you from",
    "i am learning english",
    "can you help me",
    "yes i can help you",
    "thank you",
    "you are welcome",
    "how old are you",
    "i am a computer program"
]

french_sentences = [
    "start salut end",
    "start comment allez-vous end",
    "start je vais bien end",
    "start bonjour end",
    "start bonsoir end",
    "start bonne nuit end",
    "start j'aime l'apprentissage profond end",
    "start j'aime l'IA end",
    "start quel est votre nom end",
    "start mon nom est assistant google end",
    "start j'aime apprendre end",
    "start parlez-moi de vous end",
    "start d'où venez-vous end",
    "start j'apprends l'anglais end",
    "start pouvez-vous m'aider end",
    "start oui je peux vous aider end",
    "start merci end",
    "start de rien end",
    "start quel âge avez-vous end",
    "start je suis un programme informatique end"
]

print("English Sentences")
print(english_sentences)
print("French Sentences")
print(french_sentences)

English Sentences
['hi', 'how are you', 'i am good', 'good morning', 'good evening', 'good night', 'i love deep learning', 'i love ai', 'what is your name', 'my name is google assistant', 'i like to learn', 'tell me about yourself', 'where are you from', 'i am learning english', 'can you help me', 'yes i can help you', 'thank you', 'you are welcome', 'how old are you', 'i am a computer program']
French Sentences
['start salut end', 'start comment allez-vous end', 'start je vais bien end', 'start bonjour end', 'start bonsoir end', 'start bonne nuit end', "start j'aime l'apprentissage profond end", "start j'aime l'IA end", 'start quel est votre nom end', 'start mon nom est assistant google end', "start j'aime apprendre end", 'start parlez-moi de vous end', "start d'où venez-vous end", "start j'apprends l'anglais end", "start pouvez-vous m'aider end", 'start oui je peux vous aider end', 'start merci end', 'start de rien end', 'start quel âge avez-vous end', 'start je suis un programme inf

Tokenization

1.   neural networks understand numbers,not text




In [ ]:
eng_tokenizer = Tokenizer()
eng_tokenizer.fit_on_texts(english_sentences)

fra_tokenizer = Tokenizer()
fra_tokenizer.fit_on_texts(french_sentences)

print("English Vocabulary:")
print(eng_tokenizer.word_index)
print("French Vocabulary:")
print(fra_tokenizer.word_index)

English Vocabulary:
{'you': 1, 'i': 2, 'are': 3, 'good': 4, 'am': 5, 'how': 6, 'love': 7, 'learning': 8, 'is': 9, 'name': 10, 'me': 11, 'can': 12, 'help': 13, 'hi': 14, 'morning': 15, 'evening': 16, 'night': 17, 'deep': 18, 'ai': 19, 'what': 20, 'your': 21, 'my': 22, 'google': 23, 'assistant': 24, 'like': 25, 'to': 26, 'learn': 27, 'tell': 28, 'about': 29, 'yourself': 30, 'where': 31, 'from': 32, 'english': 33, 'yes': 34, 'thank': 35, 'welcome': 36, 'old': 37, 'a': 38, 'computer': 39, 'program': 40}
French Vocabulary:
{'start': 1, 'end': 2, 'vous': 3, 'je': 4, "j'aime": 5, 'quel': 6, 'est': 7, 'nom': 8, 'de': 9, 'salut': 10, 'comment': 11, 'allez': 12, 'vais': 13, 'bien': 14, 'bonjour': 15, 'bonsoir': 16, 'bonne': 17, 'nuit': 18, "l'apprentissage": 19, 'profond': 20, "l'ia": 21, 'votre': 22, 'mon': 23, 'assistant': 24, 'google': 25, 'apprendre': 26, 'parlez': 27, 'moi': 28, "d'où": 29, 'venez': 30, "j'apprends": 31, "l'anglais": 32, 'pouvez': 33, "m'aider": 34, 'oui': 35, 'peux': 36, '

Convert Sentences into Sequences

In [ ]:
encoder_input = eng_tokenizer.texts_to_sequences(english_sentences)
decoder_input = fra_tokenizer.texts_to_sequences(french_sentences)

print("English Sequences:")
print(encoder_input)
print("French Sequences:")
print(decoder_input)

English Sequences:
[[14], [6, 3, 1], [2, 5, 4], [4, 15], [4, 16], [4, 17], [2, 7, 18, 8], [2, 7, 19], [20, 9, 21, 10], [22, 10, 9, 23, 24], [2, 25, 26, 27], [28, 11, 29, 30], [31, 3, 1, 32], [2, 5, 8, 33], [12, 1, 13, 11], [34, 2, 12, 13, 1], [35, 1], [1, 3, 36], [6, 37, 3, 1], [2, 5, 38, 39, 40]]
French Sequences:
[[1, 10, 2], [1, 11, 12, 3, 2], [1, 4, 13, 14, 2], [1, 15, 2], [1, 16, 2], [1, 17, 18, 2], [1, 5, 19, 20, 2], [1, 5, 21, 2], [1, 6, 7, 22, 8, 2], [1, 23, 8, 7, 24, 25, 2], [1, 5, 26, 2], [1, 27, 28, 9, 3, 2], [1, 29, 30, 3, 2], [1, 31, 32, 2], [1, 33, 3, 34, 2], [1, 35, 4, 36, 3, 37, 2], [1, 38, 2], [1, 9, 39, 2], [1, 6, 40, 41, 3, 2], [1, 4, 42, 43, 44, 45, 2]]


padding

---



*   padding makes all sentences of equal length



In [ ]:
encoder_input = pad_sequences(
    encoder_input,
    padding='post'
)

decoder_input = pad_sequences(
    decoder_input,
    padding='post'
)

print("English Sequences:")
print(encoder_input)
print("French Sequences:")
print(decoder_input)

English Sequences:
[[14  0  0  0  0]
 [ 6  3  1  0  0]
 [ 2  5  4  0  0]
 [ 4 15  0  0  0]
 [ 4 16  0  0  0]
 [ 4 17  0  0  0]
 [ 2  7 18  8  0]
 [ 2  7 19  0  0]
 [20  9 21 10  0]
 [22 10  9 23 24]
 [ 2 25 26 27  0]
 [28 11 29 30  0]
 [31  3  1 32  0]
 [ 2  5  8 33  0]
 [12  1 13 11  0]
 [34  2 12 13  1]
 [35  1  0  0  0]
 [ 1  3 36  0  0]
 [ 6 37  3  1  0]
 [ 2  5 38 39 40]]
French Sequences:
[[ 1 10  2  0  0  0  0]
 [ 1 11 12  3  2  0  0]
 [ 1  4 13 14  2  0  0]
 [ 1 15  2  0  0  0  0]
 [ 1 16  2  0  0  0  0]
 [ 1 17 18  2  0  0  0]
 [ 1  5 19 20  2  0  0]
 [ 1  5 21  2  0  0  0]
 [ 1  6  7 22  8  2  0]
 [ 1 23  8  7 24 25  2]
 [ 1  5 26  2  0  0  0]
 [ 1 27 28  9  3  2  0]
 [ 1 29 30  3  2  0  0]
 [ 1 31 32  2  0  0  0]
 [ 1 33  3 34  2  0  0]
 [ 1 35  4 36  3 37  2]
 [ 1 38  2  0  0  0  0]
 [ 1  9 39  2  0  0  0]
 [ 1  6 40 41  3  2  0]
 [ 1  4 42 43 44 45  2]]


Build encoder

* encoder generated hidden states for every word



In [ ]:
encoder_inputs = Input(shape=(None,))
encoder_embedding = Embedding(
    input_dim=len(eng_tokenizer.word_index) + 1,
    output_dim=64
)(encoder_inputs)
encoder_outputs, state_h, state_c = LSTM(
    units=64,
    return_sequences=True,
    return_state=True
)(encoder_embedding)
print("encoder created successfully")

encoder created successfully


Important Understanding

1.encoder_outputs:: Hidden states for all words
2.state_h : final hidden state
3.state_c :final cell state



Build decoder

In [ ]:
decoder_inputs = Input(shape=(None,))
decoder_embedding_layer = Embedding(
    input_dim=len(fra_tokenizer.word_index) + 1,
    output_dim=64
)
decoder_embedding_output = decoder_embedding_layer(decoder_inputs)

decoder_outputs, _, _ = LSTM(
    units=64,
    return_sequences=True,
    return_state=True
)(decoder_embedding_output, initial_state=[state_h, state_c])

print("decoder Created Successfully")

decoder Created Successfully


Attention layer

1.   decode outputs with enocde woutput
and dynamically focus on important words




In [ ]:
attention=Attention()
attention_output=attention([decoder_outputs, encoder_outputs])

print("Attention Layer Created Successfully")

Attention Layer Created Successfully


Combine Decoder + Attention Output

In [ ]:
decoder_combined=Concatenate(axis =- 1)([decoder_outputs,attention_output])

print("Decoder + Attention Combined Successfully")

Decoder + Attention Combined Successfully


Final Prediction Layer

In [ ]:
output = Dense(
    len(fra_tokenizer.word_index) + 1,
    activation='softmax'
)(decoder_combined)

print("Prediction Layer Created Successfully")

Prediction Layer Created Successfully


build model

In [ ]:
model=Model([encoder_inputs, decoder_inputs],output)

print("Model Created Successfully")
model.summary()

Model Created Successfully


Model: "functional_11"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_27      │ (None, None)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_28      │ (None, None)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_9         │ (None, None, 64)  │      2,624 │ input_layer_27[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_10        │ (None, None, 64)  │      2,944 │ input_layer_28[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_11 (LSTM)      │ [(None, None,     │     33,024 │ embedding_9[0][0] │
│                     │ 64), (None, 64),  │            │                   │
│                     │ (None, 64)]       │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_12 (LSTM)      │ [(None, None,     │     33,024 │ embedding_10[0][… │
│                     │ 64), (None, 64),  │            │ lstm_11[0][1],    │
│                     │ (None, 64)]       │            │ lstm_11[0][2]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attention_5         │ (None, None, 64)  │          0 │ lstm_12[0][0],    │
│ (Attention)         │                   │            │ lstm_11[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_5       │ (None, None, 128) │          0 │ lstm_12[0][0],    │
│ (Concatenate)       │                   │            │ attention_5[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, None, 46)  │      5,934 │ concatenate_5[0]… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 77,550 (302.93 KB)

 Trainable params: 77,550 (302.93 KB)

 Non-trainable params: 0 (0.00 B)

compile model

In [ ]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

train model

In [ ]:
decoder_target = np.expand_dims(decoder_input, -1)

model.fit(
    [encoder_input, decoder_input],
    decoder_target,
    epochs=50, # Increased epochs for better learning with larger dataset
    batch_size=2
)

Epoch 1/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.4286 - loss: 3.7981
Epoch 2/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4643 - loss: 3.6899
Epoch 3/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4571 - loss: 3.3029
Epoch 4/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4571 - loss: 2.5366
Epoch 5/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4857 - loss: 2.3290
Epoch 6/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5214 - loss: 2.1668
Epoch 7/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5214 - loss: 2.0732
Epoch 8/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5643 - loss: 1.9861
Epoch 9/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6000 - loss: 1.9060
Epoch 10/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6000 - loss: 1.8251
Epoch 11/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6000 - loss: 1.7552
Epoch 12/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 

## Prediction

In [ ]:
# Inference Encoder Model
encoder_model_inference = Model(encoder_inputs, [encoder_outputs, state_h, state_c])
print("Inference Encoder Model Created Successfully")

# Inference Decoder Model
decoder_inference_inputs = Input(shape=(None,)) # New input for inference decoder
decoder_state_input_h = Input(shape=(64,))
decoder_state_input_c = Input(shape=(64,))
encoder_outputs_input = Input(shape=(None, 64))

decoder_outputs_inference, state_h_inference, state_c_inference = LSTM(
    units=64,
    return_sequences=True,
    return_state=True
)(decoder_embedding_layer(decoder_inference_inputs), initial_state=[decoder_state_input_h, decoder_state_input_c])

attention_output_inference = Attention()([decoder_outputs_inference, encoder_outputs_input])
decoder_combined_inference = Concatenate(axis=-1)([decoder_outputs_inference, attention_output_inference])

output_tokens_inference = Dense(
    len(fra_tokenizer.word_index) + 1,
    activation='softmax'
)(decoder_combined_inference)

decoder_model_inference = Model(
    [decoder_inference_inputs, encoder_outputs_input, decoder_state_input_h, decoder_state_input_c],
    [output_tokens_inference, state_h_inference, state_c_inference]
)
print("Inference Decoder Model Created Successfully")

# Create a reverse word index for French for faster lookup
idx_to_word_fra = {idx: word for word, idx in fra_tokenizer.word_index.items()}

# Define a maximum sequence length for decoding based on the training data's max token length
max_decoder_sequence_length = decoder_input.shape[1] # This represents the max number of tokens

def predict_sequence(input_seq):
    # Encode the input as state vectors
    encoder_out, h, c = encoder_model_inference.predict(input_seq)

    # Generate empty target sequence of length 1 with the start token
    target_seq = np.zeros((1, 1))
    target_seq[0, 0] = fra_tokenizer.word_index['start']

    decoded_sentence = []
    # Loop for a maximum number of steps to prevent infinite loops
    for _ in range(max_decoder_sequence_length): # Limit decoding steps to max training sequence length
        output_tokens, h, c = decoder_model_inference.predict(
            [target_seq, encoder_out, h, c])

        # Sample a token (greedy search)
        sampled_token_index = np.argmax(output_tokens[0, -1, :])

        # Convert index to word. Use '' for unknown/padding (index 0 might be padding)
        sampled_word = idx_to_word_fra.get(sampled_token_index, '')

        if sampled_word == 'end':
            break # Stop if 'end' token is predicted
        elif sampled_word != '': # Only append actual words (not padding or empty strings)
            decoded_sentence.append(sampled_word)

        # Update the target sequence (of length 1) for the next step.
        target_seq = np.zeros((1, 1))
        target_seq[0, 0] = sampled_token_index

    return ' '.join(decoded_sentence).strip() # Join the collected words

print("Prediction function defined")

for i in range(len(english_sentences)):
    input_sentence = english_sentences[i]
    input_sequence = eng_tokenizer.texts_to_sequences([input_sentence])
    input_sequence_padded = pad_sequences(input_sequence, padding='post', maxlen=encoder_input.shape[1])
    translated_sentence = predict_sequence(input_sequence_padded)
    print(f"English: {input_sentence} => French: {translated_sentence}")

Inference Encoder Model Created Successfully
Inference Decoder Model Created Successfully
Prediction function defined
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
English: hi => French: programme programme programme nom nom nom nom
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
English: how are you => French: programme programme programme programme programme programme programme
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 